In [2]:
import torch
torch.cuda.is_available()

True

In [1]:
!nvidia-smi

Tue Jan 17 00:11:12 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8    12W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [20]:
random_seed = torch.manual_seed(0)

random_tensor = torch.rand(7,7)

random_seed = torch.manual_seed(0)

dot_product_tensor = torch.mm(random_tensor, torch.rand(1,7).T)
dot_product_tensor, dot_product_tensor.size()

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]), torch.Size([7, 1]))

In [6]:
# set random seed on GPU

torch.manual_seed(1234)
tensor1 = torch.rand(2,3)
device = 'cuda' if torch.cuda.is_available() else 'cpu' 
tensor1 = tensor1.to(device)
torch.manual_seed(1234)
tensor2 = torch.rand(2,3)
tensor2 = tensor2.to(device)
tensor1, tensor2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

In [9]:
mm_gpu = torch.mm(tensor1, tensor2.T)
mm_gpu, mm_gpu.size()

(tensor([[0.2299, 0.2161],
         [0.2161, 0.6287]], device='cuda:0'), torch.Size([2, 2]))

In [14]:
max_mm = torch.argmax(mm_gpu)

min_mm = torch.argmin(mm_gpu)
max_mm, min_mm

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))


10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])



In [17]:
torch.manual_seed(7)

ex10_tensor = torch.rand(1,1,1,10)
print(ex10_tensor, ex10_tensor.size())
ex10_tensor = ex10_tensor.squeeze()
print(ex10_tensor, ex10_tensor.size())

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
